import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { RootProvider } from "@/providers";

import { config } from "@/providers/wagmi-config";
import { headers } from "next/headers";
import { cookieToInitialState } from "wagmi";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialState = cookieToInitialState(config, headers().get("cookie"));
  return (
    <html lang="en">
      <body className={inter.className}>
        <RootProvider initialState={initialState}>{children}</RootProvider>
      </body>
    </html>
  );
}
