export const ChainId = {
  ETHEREUM: 1,
  ROPSTEN: 3,
  RINKEBY: 4,
  GÖRLI: 5,
  KOVAN: 42,
  POLYGON: 137,
  POLYGON_TESTNET: 80001,
  FANTOM: 250,
  FANTOM_TESTNET: 4002,
  GNOSIS: 100,
  BSC: 56,
  BSC_TESTNET: 97,
  ARBITRUM: 42161,
  ARBITRUM_NOVA: 42170,
  ARBITRUM_TESTNET: 79377087078960,
  AVALANCHE: 43114,
  AVALANCHE_TESTNET: 43113,
  OKEX: 66,
  OKEX_TESTNET: 65,
  CELO: 42220,
  PALM: 11297108109,
  MOONRIVER: 1285,
  FUSE: 122,
  TELOS: 40,
  MOONBEAM: 1284,
  OPTIMISM: 10,
  KAVA: 2222,
  METIS: 1088,
  POLYGON_ZKEVM: 1101,
  THUNDERCORE: 108,
  FILECOIN: 314,
  ZKSYNC_ERA: 324,
  LINEA: 59144,
  BASE: 8453,
  SCROLL: 534352,
  ZETACHAIN: 7000,
  CRONOS: 25,
  BLAST: 81457,
} as const;

export type ChainId = (typeof ChainId)[keyof typeof ChainId];

export const ChainKey = {
  [ChainId.ARBITRUM]: "arbitrum",
  [ChainId.ARBITRUM_NOVA]: "arbitrum-nova",
  [ChainId.ARBITRUM_TESTNET]: "arbitrum-testnet",
  [ChainId.AVALANCHE]: "avalanche",
  [ChainId.AVALANCHE_TESTNET]: "avalance-testnet",
  [ChainId.BSC]: "bsc",
  [ChainId.BSC_TESTNET]: "bsc-testnet",
  [ChainId.CELO]: "celo",
  [ChainId.ETHEREUM]: "ethereum",
  [ChainId.FANTOM]: "fantom",
  [ChainId.FANTOM_TESTNET]: "fantom-testnet",
  [ChainId.FUSE]: "fuse",
  [ChainId.GÖRLI]: "goerli",
  [ChainId.KOVAN]: "kovan",
  [ChainId.ROPSTEN]: "ropsten",
  [ChainId.POLYGON]: "polygon",
  [ChainId.POLYGON_TESTNET]: "matic-testnet",
  [ChainId.MOONBEAM]: "moonbeam",
  [ChainId.MOONRIVER]: "moonriver",
  [ChainId.OKEX]: "okex",
  [ChainId.OKEX_TESTNET]: "okex-testnet",
  [ChainId.PALM]: "palm",
  // [ChainId.PALM_TESTNET]: 'palm-testnet',
  [ChainId.RINKEBY]: "rinkeby",
  [ChainId.TELOS]: "telos",
  [ChainId.GNOSIS]: "gnosis",
  [ChainId.OPTIMISM]: "optimism",
  [ChainId.KAVA]: "kava",
  [ChainId.METIS]: "metis",
  [ChainId.POLYGON_ZKEVM]: "polygon-zkevm",
  [ChainId.THUNDERCORE]: "thundercore",
  [ChainId.ZKSYNC_ERA]: "zksync-era",
  [ChainId.LINEA]: "linea",
  [ChainId.BASE]: "base",
  [ChainId.FILECOIN]: "filecoin",
  // [ChainId.SEPOLIA]: 'sepolia',
  [ChainId.SCROLL]: "scroll",
  [ChainId.ZETACHAIN]: "zetachain",
  [ChainId.CRONOS]: "cronos",
  [ChainId.BLAST]: "blast",
} as const;
